-- 将该建表 SQL 语句，添加到 yudao-module-decoration-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "decoration_main_material_type" (
"id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
"type" varchar NOT NULL,
"unit" varchar NOT NULL,
"remark" varchar,
"reason1" varchar,
"reason2" varchar,
"tenant_id" bigint,
"creator" varchar DEFAULT '',
"create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
"updater" varchar DEFAULT '',
"update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
"deleted" bit NOT NULL DEFAULT FALSE,
PRIMARY KEY ("id")
    ) COMMENT '装修主材类型';